server:
  port: 12002
  servlet:
    context-path: /netty
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: netty

#  netty服务端口和WebSocket path
netty:
  port: 12003
  path: /ws